version: '3'

services:
  app:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/apps

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:15-alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
  postgres_data:
